# Generated by Django 5.1.7 on 2025-03-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_members_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_of_payment', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mpesa', 'M-Pesa')], max_length=10)),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.members')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contributions.contribution')),
            ],
        ),
    ]
