# Generated by Django 5.1.7 on 2025-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Widow/Widower', 'Widow/Widower'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=20)),
                ('membership_by', models.CharField(choices=[('Transfer', 'Transfer'), ('Baptism', 'Baptism')], max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('residence_address', models.CharField(max_length=200)),
            ],
        ),
    ]
