# Generated by Django 5.1.7 on 2025-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='unique_id',
            field=models.CharField(default=111111, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
