# Generated by Django 5.1.7 on 2025-03-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='unique_id',
            field=models.CharField(default=111111, editable=False, max_length=6, unique=True),
        ),
    ]
