# Generated by Django 5.1.7 on 2025-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='unique_id',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
